kind: Service
apiVersion: v1
metadata:
  name: connections-svc
spec:
  selector:
    app: connections
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connections
  labels:
    app: connections
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connections
  template:
    metadata:
      labels:
        app: connections
        appcollection: blog-aggregator
    spec:
      containers:
      - name: connections
        image: cdavisafc/cloudnative-eventlog-connections:0.0.2
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"datasource":{"url":"jdbc:mysql://mysql-svc/cookbookconnections"}}}'
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-svc:9092"
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook"
          - name: VERSIONING_TRIGGER
            value: "1"
