kind: Service
apiVersion: v1
metadata:
  name: posts-svc
spec:
  selector:
    app: posts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      name: posts
      labels:
        app: posts
        appcollection: blog-aggregator
    spec:
      containers:
      - name: posts
        image: cdavisafc/cloudnative-eventlog-posts:0.0.2
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"datasource":{"url":"jdbc:mysql://mysql-svc/cookbookposts"}}}'
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-svc:9092"
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook"
          - name: VERSIONING_TRIGGER
            value: "1"
