kind: Service
apiVersion: v1
metadata:
  name: posts-svc
spec:
  selector:
    app: posts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  labels:
    app: posts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      name: posts
      labels:
        app: posts
        appcollection: blog-aggregator
    spec:
      containers:
      - name: posts
        image: cdavisafc/cloudnative-troubleshooting-posts
        securityContext:
          privileged: true
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: SPRING_APPLICATION_JSON
            value: '{"spring":{"datasource":{"url":"jdbc:mysql://mysql-svc/cookbook"}, "zipkin":{"baseUrl":"http://zipkin-svc:9411/"}}}'
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook-posts"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://sccs-svc:8888"
          - name: SPRING_CLOUD_CONFIG_NAME
            value: "mycookbook"
          - name: SPRING_SLEUTH_SAMPLER_PERCENTAGE
            value: "0.01"
          - name: VERSIONING_TRIGGER
            value: "1"
          - name: SERVER_TOMCAT_MAX-CONNECTIONS
            value: "2"
